version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8585'
    volumes:
      - ./config.json:/app/config.json
    environment:
      - NODE_ENV=production
    restart: unless-stopped
